### PR TITLE
nelo names (Fixed, I think)

### PR DESCRIPTION
**Pull request by Hooman1130**

### CODE REVIEW

**Comment by mprotmod** [comment]
Nelo chapters have the number because they dont say the chap number on the name, if you want to change it for the name, put the chap number first and then the name.

something like this.

'Ch  ' + (chaptersArray.length - x) + ' | ' + chapLink.textContent

**Comment by Hooman1130** [comment]
they do have the number in the name tho

**Comment by Hooman1130** [comment]
I figured something out. the chapter number is always there and at the beginning, but if there's a volume number it's blocked sometimes. so, I did `chapLink.textContent.replace('Chapter ', 'Ch.').replace('Vol','V')`

**Comment by Hooman1130** [comment]
I'm not exactly sure how to edit pull requests, so I'll close this one and make a new one.

**Pull request closed without merging**
