### PR TITLE
Update moduleTemplate.json

### PR DESCRIPTION
**Pull request by Bilna95**
added two new layout + change version

### CODE REVIEW

**Comment by Bilna95** [comment]
Don't accept the pull request it seems that the search option is broken now I will upload the right version in the day.

**Comment by mprotmod** [comment]
Only keep the mainpage.html that you are going to use, dont use 2 different mainpage.html for different layouts. You use 2 mainpages.html in case you were doing multirequest for the mainpage and you needed 2 different javascripts.

Delete the html from the mainpage, only keep the javascript.

**Comment by Bilna95** [comment]
It should be fine now. It was just a different version of the mainpage code with more design to it.

**Comment by Bilna95** [comment]
up

**Comment by Bilna95** [comment]
Plz susuya

**Pull request merged**
